### ISSUE TITLE
infografia sistemas numericos_Victor Noe Osorio Sanchez

### ISSUE THREAD

**Issue by Victor-noe12** [SistemasTecTlaxiaco/infografia-Victor-noe12#1]
[Infografía (1).pdf](https://github.com/user-attachments/files/16821060/Infografia.1.pdf)

**Comment by Alondra-oss** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:14/14
Referencias:14/14
Presentación:14/14
Calificación Final : 19.8/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
